# Generated by Django 6.0.3 on 2026-05-06 15:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating_id', models.IntegerField()),
                ('codi', models.CharField(max_length=10, verbose_name='Codi')),
                ('age', models.IntegerField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_ratings', to='web_app.api')),
            ],
            options={
                'unique_together': {('age_rating_id', 'api')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Staff', 'Staff'), ('Admin', 'Admin'), ('Consumer', 'Consumer')], default='Consumer', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscribed_users', to='web_app.api')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField()),
                ('country', models.CharField(max_length=255)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='web_app.api')),
            ],
            options={
                'unique_together': {('director_id', 'api')},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='web_app.api')),
            ],
            options={
                'unique_together': {('genre_id', 'api')},
            },
        ),
        migrations.CreateModel(
            name='Contingut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_content_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name="ID de l'API")),
                ('titol', models.CharField(max_length=255, verbose_name='Títol')),
                ('data_estrena', models.IntegerField(blank=True, null=True, verbose_name="Any d'estrena")),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('age_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.agerating')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.api')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.director')),
                ('genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.genre')),
            ],
            options={
                'verbose_name': 'Contingut',
                'verbose_name_plural': 'Continguts',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='web_app.contingut')),
            ],
            options={
                'verbose_name': 'Pel·lícula',
                'verbose_name_plural': 'Pel·lícules',
            },
        ),
        migrations.CreateModel(
            name='Preferits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afegit_a', models.DateTimeField(auto_now_add=True)),
                ('contingut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.contingut')),
            ],
            options={
                'verbose_name': 'Preferit',
                'verbose_name_plural': 'Preferits',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_temporades', models.IntegerField(blank=True, null=True, verbose_name='Nombre de temporades')),
                ('contingut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='web_app.contingut')),
            ],
            options={
                'verbose_name': 'Sèrie',
                'verbose_name_plural': 'Sèries',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferits', models.ManyToManyField(blank=True, through='web_app.Preferits', to='web_app.contingut')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='preferits',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferits_set', to='web_app.userprofile'),
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.IntegerField()),
                ('comentari', models.TextField(blank=True, null=True)),
                ('creada_a', models.DateTimeField(auto_now_add=True)),
                ('contingut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracions', to='web_app.contingut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoració',
                'verbose_name_plural': 'Valoracions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='preferits',
            unique_together={('user_profile', 'contingut')},
        ),
    ]
