# Generated by Django 6.0.3 on 2026-04-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='records_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='records_updated',
            field=models.IntegerField(default=0),
        ),
    ]
