# Generated by Django 6.0.3 on 2026-05-08 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualitzacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualitzacio', models.DateTimeField(auto_now_add=True)),
                ('contingut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualitzacions', to='web_app.contingut')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualitzacions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualització',
                'verbose_name_plural': 'Visualitzacions',
            },
        ),
    ]
