# Generated by Django 6.0.3 on 2026-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingut',
            name='api_content_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="ID de l'API"),
        ),
    ]
