# Generated by Django 6.0.3 on 2026-05-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_visualitzacio_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_role', models.CharField(max_length=50)),
                ('new_role', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log de Roles',
                'verbose_name_plural': 'Audit Logs de Roles',
                'ordering': ['-timestamp'],
            },
        ),
    ]
