# Generated by Django 6.0.3 on 2026-04-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
