# Generated by Django 6.0.3 on 2026-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_contingut_api_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingut',
            name='poster_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
