# Generated by Django 6.0.3 on 2026-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_contingut_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Staff Admin', 'Staff Admin'), ('Admin', 'Admin'), ('Consumer', 'Consumer')], default='Consumer'),
        ),
    ]
