name: Pareto Diagram
on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Get JSON
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      run: |

        gh issues list --state open --json title,body,labels > issues.json

        
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas json 
    - name: get graphics
      run: |
        python .github/scripts/name.py
